apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j27bw7q5h-dotnet-basic
  janus-idp.io/tekton: j27bw7q5h-dotnet-basic
  backstage.io/kubernetes-id: j27bw7q5h-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j27bw7q5h-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
